services:
  jenkins:
    image: yassinechrigui/docker:tag001
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins

  trivy:
    image: aquasec/trivy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - trivy_cache:/root/.cache
    entrypoint: ["trivy"]

volumes:
  jenkins_home:  # Defines the named volume for Jenkins data
  trivy_cache:   # Defines the named volume for Trivy cache

