version: '3.8'

services:
  # Backend Spring Service
  backend-foyer:
    image: docker.io/yassinechrigui/docker:tag001
    build:
      context: .
      args:
        NEXUS_USER: "admin"
        NEXUS_PASSWORD: "admin"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tpFoyer17?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"
    depends_on:
      - db
    restart: on-failure

  # MySQL Database Service
  db:
    container_name: db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tpFoyer17
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Frontend Angular Service
  front_foyer:
    image: YassineChrigui_Gr4_5SE2/Yassine
    container_name: Front_Foyer
    ports:
      - "4200:80"
    depends_on:
      - backend-spring
    networks:
      - my-network

  # Trivy Vulnerability Scanner
  trivy:
    image: aquasec/trivy:latest
    container_name: trivy
    volumes:
      - /var/run/docker.sock
    entrypoint: ["trivy", "image", "--format", "json", "--cache-dir", "/root/.cache", "backend-spring"]

# Volumes to persist data
volumes:
  mysql-data:

# Optional networks for isolation
networks:
  my-network:
    driver: bridge
